-- -----------------------------------------------------------------------
-- BigQuery Federated Queries for Real-Time Fraud Detection
-- Purpose: Join live data from AlloyDB with historical BigQuery data 
-- without any ETL pipeline.
-- -----------------------------------------------------------------------

-- 1. Real-Time Fraud Scoring and Feature Augmentation Query
-- The goal is to join the LATEST PENDING transaction from AlloyDB (t) 
-- with the historical risk profile (risk) from BigQuery.
-- This query returns the complete feature set required for the final ML scoring mechanism.
SELECT
    t.transaction_id,
    t.customer_id,
    t.transaction_amount,
    t.device_fingerprint,
    risk.risk_score,               -- Feature 1: Historical ML Score (from BQ)
    risk.risk_segment,             -- Feature 2: Historical Segment (from BQ)
    t.transaction_timestamp
FROM
    -- **Federated Query (AlloyDB): Pulls only the most recent pending transactions**
    EXTERNAL_QUERY(
        'us-central1.alloydb_fraud_detect',
        '''
        SELECT
            transaction_id, customer_id, transaction_amount, transaction_timestamp, device_fingerprint
        FROM 
            public.live_transactions 
        WHERE 
            status = 'PENDING' 
            --AND transaction_timestamp >= NOW() - INTERVAL '3 minutes' 
        LIMIT 10 
        '''
    ) AS t
LEFT JOIN
    -- **BigQuery (Historical): Joins the live transaction with the risk profile**
    `my-alloydb-project-vivekshinde.bq_fraud_detection.historical_risk_profile` AS risk
ON t.customer_id = risk.customer_id
ORDER BY t.transaction_timestamp DESC;



-- ----------------------------------------------------------------------------------
-- 2. Hybrid RAG Federated Query Example (Vector Search Focus for Investigation)
-- Joins the vector search output (AlloyDB) with BigQuery data.
-- This query assumes a real-time query embedding is generated by the application layer.
-- Purpose: Find suspicious behavioral patterns (Vector Search on AlloyDB) and 
-- augment the result with historical fraud status (BigQuery).
-----------------------------------------------------------------------------------
SELECT
    ud.customer_id,
    ud.log_summary,
    ud.context_source,
    risk.bqml_risk_score AS Historical_Risk_Score -- Augmentation from BQ
FROM
    -- **Federated Query (AlloyDB): Perform real-time vector search on unstructured data**
    EXTERNAL_QUERY(
        'us-central1.alloydb_fraud_detect',
        '''
        -- Perform vector search against customer communication/log data
        SELECT 
            customer_id, log_summary, context_source 
        FROM 
            public.customer_unstructured_data
        WHERE 
            log_embedding <=> '[0.9, 0.1, 0.5]' -- Find customers with similar log patterns 
        ORDER BY 
            log_embedding <=> '[0.9, 0.1, 0.5]' -- Order by distance (similarity)
        LIMIT 5
        '''
    ) AS ud
LEFT JOIN
    -- **BigQuery (Historical): Joins the vector search results with the static ML risk profile**
    `my-alloydb-project-vivekshinde.bq_fraud_detection.historical_risk_profile` AS risk
ON ud.customer_id = risk.customer_id;

-- ----------------------------------------------------------------------------------
-- FILE 4: BigQuery Federated Query - Real-Time Fraud Monitoring Dashboard
-- Purpose: Generate key metrics for a real-time monitoring dashboard, combining 
--          historical risk (BQ) with current transactional velocity (AlloyDB).
-- ----------------------------------------------------------------------------------

-- NOTE: Replace placeholders for connection and project/dataset.
-- This query aggregates data and returns a single row for a dashboard tile/KPI card.

WITH Historical_Risk_Summary AS (
    -- Step 1: BigQuery side - Query large, historical/static data for context.
    SELECT
        COUNT(customer_id) AS total_high_risk_customers,
        SUM(CASE WHEN risk_segment = 'HIGH' OR risk_segment = 'CRITICAL' THEN 1 ELSE 0 END) AS total_critical_customers,
        AVG(risk_score) AS overall_historical_risk_avg
    FROM
        `my-alloydb-project-vivekshinde.bq_fraud_detection.historical_risk_profile`
),

Live_Transaction_Velocity AS (
    -- Step 2: Federated Query - Pulls real-time operational data from AlloyDB.
    -- Aggregation is pushed down to AlloyDB for speed.
    SELECT
    total_txns_last_5min,
    pending_score_count,
    last_txn_time
    FROM
    EXTERNAL_QUERY(
        'us-central1.alloydb_fraud_detect',
        '''
        SELECT 
            COUNT(transaction_id) AS total_txns_last_5min,
            SUM(CASE WHEN status = 'PENDING' THEN 1 ELSE 0 END) AS pending_score_count,
            MAX(transaction_timestamp) AS last_txn_time
        FROM 
            public.live_transactions
        --WHERE
        --    transaction_timestamp >= NOW() - INTERVAL '5 minutes'
        '''
    )
)

-- Step 3: Final Join - Combines historical context with live operational metrics.
SELECT
    'Fraud Monitoring Snapshot' AS Report_Title,
    -- Historical Metrics (BQ)
    T1.total_high_risk_customers,
    T1.total_critical_customers,
    T1.overall_historical_risk_avg,
    
    -- Live Operational Metrics (AlloyDB)
    T2.total_txns_last_5min,      -- Current volume
    T2.pending_score_count,       -- Alert metric: How many are waiting for scoring
    T2.last_txn_time              -- Freshness metric
FROM 
    Historical_Risk_Summary AS T1
CROSS JOIN
    Live_Transaction_Velocity AS T2
LIMIT 1; -- Ensures fast return for the dashboard tile.
